name: create-tf-workspace

on:
  workflow_dispatch:
    inputs:
      TF_organization:
        description: 'The Terraform cloud organization that is associated with the secret token.'
        required: true
      GH_BRANCH:
        description: 'Github Branch to associate with terraform cloud run.'
        required: true
        default: 'main'

jobs:
  create-tf-workspace:
    runs-on: macos-latest

    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get Github Org name
        shell: bash
        run: | 
          echo "GH_ORGANIZATION=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV

      - name: Get Github Repo name
        shell: bash
        run: |
          echo "GH_REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Create Terraform Cloud workspace
        shell: bash
        run: |
          chmod +x ./scripts/create-workspaces.sh
          ./scripts/create-workspaces.sh ${{ secrets.TOKEN }} ${{ secrets.OAUTH_TOKEN_ID }} $GH_REPO_NAME $GH_ORGANIZATION ${{ github.event.inputs.GH_BRANCH }} ${{ github.event.inputs.TF_organization }}